### ISSUE TITLE
offset icons / text overflow

### ISSUE THREAD

**Issue by jenmhoang** [calblueprint/dccentralkitchen#104]
- "Accepts Healthy Rewards" almost cut off at bottom.
- Icons not centered.
![IMG_4013](https://user-images.githubusercontent.com/34316838/79676554-33133700-819c-11ea-985d-7cd18696812f.PNG)
![IMG_4012](https://user-images.githubusercontent.com/34316838/79676559-360e2780-819c-11ea-9c52-3ea19ee65285.PNG)

**Comment by wangannie** [comment]
Which icons specifically?

**Comment by jenmhoang** [comment]
oop sorryfor complete lack of elaboration, the menu hamburger and the location icon on the top left of the second pic

**Comment by wangannie** [comment]
Addressed the text overflow issue in #134 and decided that icon alignment is not a priority within the time constraints.
