### ISSUE TITLE
Scaling the map 

### ISSUE THREAD

**Issue by karinanguyen** [calblueprint/dccentralkitchen#106]
When the user zooms out on the map, it becomes clustered and nothing can be seen. Maybe get rid of the text with such interaction and remain only the location icons. 

![IMG_0667](https://user-images.githubusercontent.com/47619897/79676611-ac128e80-819c-11ea-9748-dd0753d2eb7f.PNG)

**Comment by wangannie** [comment]
Repeat of #105
