### ISSUE TITLE
[UX][Android] Unable to swipe left on Android to show the hamburger menu

### ISSUE THREAD

**Issue by JustinMi** [calblueprint/dccentralkitchen#107]
On most Android apps you can open a hamburger menu by swiping left from the left edge of the phone (or swipe right if your hamburger menu opens from the right). For a real-life example, if you swipe left on your Uber or Lyft app, it would open the menu. I think it's common enough that it's kind of an expected behavior for apps, but DC doesn't have it. It would increase usability a lot if you could implement it!

**Comment by wangannie** [comment]
This is actually something I intentionally disabled. On the main map screen, there are already a lot of swiping gestures involved with navigating around the map itself, as well as horizontal scrolling within the product drawer, so additional swipe behavior would easily be triggered accidentally.

Also, I checked the Uber and Lyft apps and neither have the ability to swipe to open the hamburger menu, presumably for the same reason preventing interference with the map.

**Comment by JustinMi** [comment]
Did you check on the Android version or iOS? I only have an Android phone so I can only speak on that, but on Android, you can swipe left from the left edge of the screen to open the menu on Lyft and Uber. I'm guessing they can differentiate between swiping left from the left edge of the screen, which opens the menu, with a generic left swipe anywhere else, which navigates the map. I checked other Android apps with a hamburger like Notion, Twitter, and Slack, and they can swipe to open too.

 Not sure how hard that is to implement though--is it possible in our case?

**Comment by wangannie** [comment]
Resolved in #163
