### ISSUE TITLE
UI nitpick: Can't see your exact current location on map

### ISSUE THREAD

**Issue by rlhe811** [calblueprint/dccentralkitchen#109]
![IMG_4441](https://user-images.githubusercontent.com/46945934/79676678-17189100-81ae-11ea-8366-80b14a243b1d.PNG)

**Comment by rlhe811** [comment]
Idk if this makes sense but you can sort of see the general area I guess but there's no marker for your position.

**Comment by wangannie** [comment]
If you zoom all the way out to your true location, you should be able to see your location marker (blue dot). We have the default set to open to the DC area if you're over 100 miles away so your current location isn't shown within the scope. It is a really good point that this could be really confusing with the Recenter Location button that takes you to our central store (Dollar Plus Howard).
