### ISSUE TITLE
[Android//Pixel 3] Could not log in as guest

### ISSUE THREAD

**Issue by ntalcus** [calblueprint/dccentralkitchen#118]
### To replicate:
* On Pixel 3, click the log in as guest text/button
* Nothing happens for me

### Rundown
Not much to add to above

**Comment by wangannie** [comment]
Was there any visual response on the button that might appear like it was clicked like the usual `TouchableOpacity` animation where it goes white when selected?

**Comment by anniero98** [comment]
Lois noticed this too while we were testing yesterday - she said it worked eventually but she essentially was tapping the button until it went through (LOL)

**Comment by wangannie** [comment]
I had trouble recreating this, even on my PIxel 3 emulator. I tried tackling it in #121 by adding padding to increase the clickable area because I noticed it was rather small and close to the other buttons, but I guess this issue persists.
