### ISSUE TITLE
Get Directions shows multiple stores

### ISSUE THREAD

**Issue by 12aschen** [calblueprint/dccentralkitchen#136]
- Switch Get Directions button back to showing exact coordinates

- Came up from a user tester that Uptown Market (her local store) showed two stores, one in DC and one in Arlington
- Told her about coordinates as alternative and she said she much preferred that, since she would be checking it for directions rather than for store info (already provided in our app!) 
- Have found similar issues with DC Food Market, Capitol Market, Kwik Stop, but it seems to vary by user (screenshots below of what is pulled up)

![image](https://user-images.githubusercontent.com/55964132/80667807-0214eb00-8a55-11ea-8eb0-149dba1e04e6.png)
![image](https://user-images.githubusercontent.com/55964132/80667838-10630700-8a55-11ea-98bf-77cf52e726c9.png)
![image](https://user-images.githubusercontent.com/55964132/80667843-12c56100-8a55-11ea-883b-c588d172f7f1.png)
(DC Food Market shows every DC store that sells food and has 'market' in the name :'))

**Comment by wangannie** [comment]
Add `googleForceLatLon: true`
