### ISSUE TITLE
Upgrade react-navigation to v5, upgrade Expo to SDK 36

### ISSUE THREAD

**Issue by anniero98** [calblueprint/dccentralkitchen#52]
React Navigation 5 was released in February (a breaking release): https://reactnavigation.org/blog/2020/02/06/react-navigation-5.0/

Expo SDK 36 was released in December: https://blog.expo.io/expo-sdk-36-is-now-available-b91897b437fe

Creating a single issue because I feel like these are best addressed together.

* Note that it looks like they'll be doing some updates in SDK 37 to work with the new react-navigation v5 changes; at the very least with the stack, so as the comment says YMMV with the two interacting for now
https://expo.canny.io/feature-requests/p/support-react-navigation-5x-native-stack

**Comment by thumn** [comment]
Upgrading to Expo SDK 37 since it was just released: https://blog.expo.io/expo-sdk-37-is-now-available-dd5770f066a6

**Comment by thumn** [comment]
@12aschen looks like "Points History" on the drawer is too big to fit :( should we make the font size smaller?
